version: '3.8'

services:
  mongo1:
    image: mongo:5.0.25
    container_name: mongo1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /path/to/your/first/data/directory:/data/db # 替换为您的第一个数据目录路径
      - ./mongo-init-readonly.sh:/docker-entrypoint-initdb.d/mongo-init-readonly.sh # 可选的初始化脚本
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:5.0.25
    container_name: mongo2
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - /path/to/your/second/data/directory:/data/db # 替换为您的第二个数据目录路径
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
